"""add_integration_tables

Revision ID: ee495df5c62a
Revises: 007
Create Date: 2026-02-11 12:29:14.544995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee495df5c62a'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('sync_schedule', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integrations_next_sync', 'integrations', ['next_sync_at'], unique=False)
    op.create_index('ix_integrations_org_id', 'integrations', ['org_id'], unique=False)
    op.create_index('ix_integrations_provider', 'integrations', ['provider'], unique=False)
    op.create_index('ix_integrations_status', 'integrations', ['status'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_logs_integration_id', 'sync_logs', ['integration_id'], unique=False)
    op.create_index('ix_sync_logs_started_at', 'sync_logs', ['started_at'], unique=False)
    op.create_index('ix_sync_logs_status', 'sync_logs', ['status'], unique=False)
    op.create_table('integration_field_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('data_field_id', sa.UUID(), nullable=False),
    sa.Column('external_field_name', sa.String(length=500), nullable=False),
    sa.Column('external_field_label', sa.String(length=500), nullable=True),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('filter_criteria', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_field_id'], ['data_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'external_field_name', 'data_field_id', name='uq_mapping_integration_ext_field')
    )
    op.create_index('ix_field_mappings_data_field_id', 'integration_field_mappings', ['data_field_id'], unique=False)
    op.create_index('ix_field_mappings_integration_id', 'integration_field_mappings', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_mappings_integration_id', table_name='integration_field_mappings')
    op.drop_index('ix_field_mappings_data_field_id', table_name='integration_field_mappings')
    op.drop_table('integration_field_mappings')
    op.drop_index('ix_sync_logs_status', table_name='sync_logs')
    op.drop_index('ix_sync_logs_started_at', table_name='sync_logs')
    op.drop_index('ix_sync_logs_integration_id', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index('ix_integrations_status', table_name='integrations')
    op.drop_index('ix_integrations_provider', table_name='integrations')
    op.drop_index('ix_integrations_org_id', table_name='integrations')
    op.drop_index('ix_integrations_next_sync', table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
